version: 1.0.{build}
image: Ubuntu1604
environment:
  JD_COOKIE:
    secure: viXNDVb511n0H20Z4AB4BteWPoewXGA5Ff3eqbiVV4syxeAH6x9XCSB1SMMnPtPtrN1KIzlAOw14nnTy0Jhak5V8tbxobFtp0w/d9qpCCK9Zz+rXEQ36DPHjknXbsRgULucsxhokR5Kd9zvZyq7hZg==
  access_token:
    secure: K199qWuP1K8338fEplq9uOKZdYJiFaVl2pWjizcgrU5DXna/Rn5ac5P6WbSnuscb
init:
  - sh: git config --global credential.helper store
  - ps: Set-Content -Path "$HOME\.git-credentials" -Value "https://oauth2:$($env:access_token)@gitee.com`n" -NoNewline
clone_script:
  - git clone "https://gitee.com/LinRaise/Auto-jd.git" .
install:
  - sh: >-
      nvm install node
      nvm install-latest-npm
      node -v
      npm -v
build_script:
  - npm install

  - sh: >-
      ls jd_*.js | xargs -i node {}