version: 1.0.{build}
image: Ubuntu2004
environment:
  access_token:
    secure: K199qWuP1K8338fEplq9uOKZdYJiFaVl2pWjizcgrU5DXna/Rn5ac5P6WbSnuscb
init:
- sh: echo Init script
clone_script:
- sh: echo clone_script
install:
- sh: echo install
build_script:
- sh: >-
    git clone "https://oauth2:$($env:access_token)@gitee.com/LinRaise/auto-jd.git" .
    npm install
    ls jd_*.js | xargs -i node {}
test_script:
- sh: echo test
on_success:
- sh: echo success
on_failure:
- sh: echo Ooops, failed!
on_finish:
- sh: echo Well done, build completed!
on_image_bake:
- sh: echo Image bake script