version: 1.0.{build}
branches:
  only:
  - main
image: Visual Studio 2019
environment:
  JD_COOKIE: pt_key=AAJhTsPNADBHhaxh7bdzLYWImYnL86GIlgGEHtvDbZJxKEPfkgFuN93I7Omcu2ziqT7XO1dhZbM;pt_pin=jd_5006e4d4017b2;
  #  secure: viXNDVb511n0H20Z4AB4BteWPoewXGA5Ff3eqbiVV4syxeAH6x9XCSB1SMMnPtPtrN1KIzlAOw14nnTy0Jhak5V8tbxobFtp0w/d9qpCCK9Zz+rXEQ36DPHjknXbsRgULucsxhokR5Kd9zvZyq7hZg==
  access_token:
    secure: K199qWuP1K8338fEplq9uOKZdYJiFaVl2pWjizcgrU5DXna/Rn5ac5P6WbSnuscb
init:
  - sh: git config --global credential.helper store
  - ps: Set-Content -Path "$HOME\.git-credentials" -Value "https://oauth2:$($env:access_token)@gitee.com`n" -NoNewline
   # - ps: Set-Content -Path "$HOME\.git-credentials" -Value "https://$($env:access_token):x-oauth-basic@github.com`n" -NoNewline

install:
  - sh: git clone "https://gitee.com/LinRaise/auto-jd.git" .
  - npm install
  - sh: ls
  - node jd_bean_sign.js
build_script: off
  # - sh: ls jd_*.js | xargs -i node {}
test: off
on_success:
  - echo "Transform complete!"
deploy: off